preco = (1.75, 2.00, 15.90, 25.00, 4.20, 9.99, 120.32, 22.30, 34.90)
produto = ('Lápis', 'Borracha', 'Caderno', 'Estojo', 'Transferidor', 'Compasso', 'Mochila', 'Canetas', 'Livro')
print('---'*20)
print('                 LISTAGEM DE PREÇOS            ')
print('---'*20)
print(f'{produto[0]:.<30} ........................ R${preco[0]:>7.2f}')
print(f'{produto[1]:.<30} ........................ R${preco[1]:>7.2f}')
print(f'{produto[2]:.<30} ........................ R${preco[2]:>7.2f}')
print(f'{produto[3]:.<30} ........................ R${preco[3]:>7.2f}')
print(f'{produto[4]:.<30} ........................ R${preco[4]:>7.2f}')
print(f'{produto[5]:.<30} ........................ R${preco[5]:>7.2f}')
print(f'{produto[6]:.<30} ........................ R${preco[6]:>7.2f}')
print(f'{produto[7]:.<30} ........................ R${preco[7]:>7.2f}')
print(f'{produto[8]:.<30} ........................ R${preco[8]:>7.2f}')
