times = ('internacional', 'são paulo', 'flamengo', 'atletico - MG', 'palmeiras', 'grêmio', 'fluminense', 'ceará - SC', 'corinthians',
         'santos', 'athlitico - PR', 'athlitico - GO', 'brangantino', 'sport Recife', 'vasco da gama', 'fortaleza', 'bahia', 'goiás', 'coritiba', 'botafogo')
trimes = times.index('santos')
print('Times brasileirão 2020')
print('-=-'*20)
print(f'Lista de times do brasileirão: {times}')
print('-=-'*20)
print(f'Os cinco primeiros são: {times[:5]}')
print('-=-'*20)
print(f'Os ultimos quatro times são: {times[16:20]}')
print('-=-'*20)
print(f'Os times em ordem alfabética: {sorted(times)}')
print('-=-'*20)
print(f'O santos está em: {trimes+1}° lugar na tabela !')
print('-=-'*20)
